# Generated by Django 5.0.3 on 2024-06-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_app', '0002_user_last_login_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
